import Toybox.Lang;

//! Exchange holidays, generated by tools/generate_holidays.py — do not edit by hand.
//! Generated: 2026-09-01
//!
//! Weekends are a rule the watch can compute; holidays are not. Chinese New Year and
//! Diwali move with lunar calendars, Easter moves with its own, and exchanges add one-off
//! closures for national mourning or systems testing. So they are tabulated, from each
//! exchange's own published calendar.
//!
//! **The table has an edge, and the watch respects it.** An exchange only publishes a year
//! or so ahead — when this was generated neither Shanghai nor Mumbai had a 2027 calendar in
//! existence. Each market therefore records the last year it is good for, and outside that
//! range no holidays are applied rather than wrong ones. Re-run the generator when the
//! calendars are published; `LAST_COVERED_YEAR` below is what tells you it is time.
(:glance)
module Holidays {

    //! The last calendar year each market has holiday data for, in Markets.NAMES order.
    //! Outside it the market is treated as having no holidays at all.
    var LAST_COVERED_YEAR as Array<Number> = [
        2027, // Sydney
        2027, // Tokyo
        2027, // Taipei
        2026, // Singapore
        2027, // Hong Kong
        2026, // Shanghai
        2026, // Mumbai
        2027, // Europe
        2027, // Toronto
        2027, // New York
        2027  // NASDAQ
    ] as Array<Number>;

    //! Where each market's run of dates starts in DAYS. One extra entry on the end holds
    //! the total, so a market's slice is always OFFSETS[i] to OFFSETS[i + 1].
    var OFFSETS as Array<Number> = [
        0, 14, 50, 83, 93, 120, 145, 160, 167, 187, 207, 227
    ] as Array<Number>;

    //! Every closure, as days since 1970-01-01, market by market and ascending within each
    //! so the lookup can bisect. Same representation Zones.daysFromCivil returns.
    var DAYS as Array<Number> = [
        // Sydney — 14 closures through 2027
        20454, 20479, 20546, 20549, 20612, 20812, 20815, 20819,
        20844, 20903, 20906, 20983, 21179, 21180,
        // Tokyo — 36 closures through 2027
        20454, 20455, 20465, 20495, 20507, 20532, 20572, 20577,
        20578, 20579, 20654, 20676, 20717, 20718, 20719, 20738,
        20760, 20780, 20818, 20819, 20829, 20860, 20872, 20899,
        20937, 20941, 20942, 20943, 21018, 21041, 21081, 21084,
        21102, 21125, 21145, 21183,
        // Taipei — 33 closures through 2027
        20454, 20496, 20497, 20500, 20501, 20502, 20503, 20504,
        20511, 20546, 20549, 20574, 20623, 20721, 20724, 20735,
        20752, 20812, 20819, 20853, 20854, 20857, 20858, 20859,
        20878, 20913, 20938, 20978, 21076, 21089, 21102, 21116,
        21183,
        // Singapore — 10 closures through 2026
        20454, 20501, 20502, 20546, 20574, 20600, 20605, 20675,
        20766, 20812,
        // Hong Kong — 27 closures through 2027
        20454, 20501, 20502, 20503, 20546, 20549, 20550, 20574,
        20598, 20623, 20635, 20727, 20745, 20812, 20819, 20857,
        20858, 20903, 20906, 20913, 20951, 20978, 21000, 21077,
        21092, 21099, 21179,
        // Shanghai — 25 closures through 2026
        20454, 20455, 20500, 20501, 20502, 20503, 20504, 20507,
        20546, 20549, 20550, 20574, 20577, 20578, 20598, 20623,
        20635, 20721, 20727, 20728, 20731, 20732, 20733, 20745,
        20812,
        // Mumbai — 15 closures through 2026
        20479, 20515, 20538, 20543, 20546, 20557, 20574, 20601,
        20630, 20710, 20728, 20746, 20767, 20781, 20812,
        // Europe — 7 closures through 2027
        20454, 20546, 20549, 20812, 20819, 20903, 20906,
        // Toronto — 20 closures through 2027
        20454, 20500, 20546, 20591, 20635, 20668, 20703, 20738,
        20812, 20815, 20819, 20864, 20903, 20962, 21000, 21032,
        21067, 21102, 21179, 21180,
        // New York — 20 closures through 2027
        20454, 20472, 20500, 20546, 20598, 20623, 20637, 20703,
        20783, 20812, 20819, 20836, 20864, 20903, 20969, 20987,
        21004, 21067, 21147, 21176,
        // NASDAQ — 20 closures through 2027
        20454, 20472, 20500, 20546, 20598, 20623, 20637, 20703,
        20783, 20812, 20819, 20836, 20864, 20903, 20969, 20987,
        21004, 21067, 21147, 21176
    ] as Array<Number>;

    //! Is this market shut for a holiday on this day?
    //!
    //! `day` is a day number in the market's own local calendar, which is what the table
    //! holds — a holiday is a date where the exchange is, not an instant.
    function isClosed(market as Number, day as Number, year as Number) as Boolean {
        if (year > LAST_COVERED_YEAR[market]) {
            return false;   // past the published calendar: assume nothing
        }

        // Bisect the market's slice. Fourteen markets times a linear scan of thirty odd
        // dates, twelve days deep, is enough work to matter inside a glance.
        var low = OFFSETS[market];
        var high = OFFSETS[market + 1] - 1;

        while (low <= high) {
            var mid = low + (high - low) / 2;
            var value = DAYS[mid];
            if (value == day) {
                return true;
            }
            if (value < day) {
                low = mid + 1;
            } else {
                high = mid - 1;
            }
        }
        return false;
    }
}
